<?php
// $Id: site_tour.module,v 1.3.2.1.2.4 2009/01/29 21:36:46 stefano73 Exp $

/**
 * @file
 * Create site tours with Amberjack (http://amberjack.org Copyright (C) 2006 Arash Yalpani <arash@yalpani.de>).
 */

/**
 * Implementation of hook_menu().
 */
function site_tour_menu() {
  $items = array();

  $items['site_tour'] = array(
    'page callback' => 'site_tour_render',
    'access callback' => 'user_access',
    'access arguments' => array('view site tours'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/content/site_tour'] = array(
    'title' => t('Site tours'),
    'description' => t('Manage site tours.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_tour_admin_list'),
    'access callback' => 'user_access',
    'access arguments' => array('manage site tours'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'site_tour.admin.inc',
  );
  $items['admin/content/site_tour/list'] = array(
    'title' => t('Site tours'),
    'description' => t('Manage site tours.'),
    'access callback' => 'user_access',
    'access arguments' => array('manage site tours'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'file' => 'site_tour.admin.inc',
  );
  $items['admin/content/site_tour/add'] = array(
    'title' => t('Add site tour'),
    'description' => t('Add a new site tour.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_tour_admin_edit'),
    'access callback' => 'user_access',
    'access arguments' => array('manage site tours'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,   
    'file' => 'site_tour.admin.inc',
  );
  $items['admin/content/site_tour/edit/%'] = array(
    'title' => t('Edit tour'),
    'description' => t('Edit a site tour.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_tour_admin_edit', 4),
    'access callback' => 'user_access',
    'access arguments' => array('manage site tours'),
    'type' => MENU_CALLBACK,
    'file' => 'site_tour.admin.inc',
  );
  $items['admin/content/site_tour/edit/%/tour'] = array(
    'title' => t('Edit tour'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );  
  $items['admin/content/site_tour/edit/%/pages'] = array(
    'title' => t('Edit pages'),
    'description' => t('Edit site tour pages.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_tour_admin_edit_pages', 4),
    'access callback' => 'user_access',
    'access arguments' => array('manage site tours'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    'file' => 'site_tour.admin.inc',
  );
  $items['admin/content/site_tour/edit/%/pages/%'] = array(
    'title' => t('Edit page'),
    'description' => t('Edit site tour page.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_tour_admin_edit_page', 4, 6),
    'access callback' => 'user_access',
    'access arguments' => array('manage site tours'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'file' => 'site_tour.admin.inc',
  );  

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function site_tour_perm() {
  return array('view site tours', 'manage site tours');
}

/**
 * Implementation of hook_perm().
 */
function site_tour_theme() {
  return array(
    'site_tour' => array(
      'arguments' => array(),
    ),  
    'site_tour_list' => array(
      'arguments' => array(),
    ),
    'site_tour_page' => array(
      'arguments' => array(),
    ),
    'site_tour_pages' => array(
      'arguments' => array(),
    ),
    'site_tour_page_add' => array(
      'arguments' => array(),
    ),    
  );
}

function site_tour_init() {
  if ($_GET['tourId']) {
    $path = drupal_get_path('module', 'site_tour').'/lib/';
    drupal_add_js($path.'amberjack.pack.js');
  }
}

/**
 * Implementation of hook_footer().
 */
function site_tour_footer() {
  if (!$_GET['tourId']) return;

  // select the tour
  $tour = db_fetch_object(db_query('SELECT * FROM {site_tour} WHERE url="%s" AND status=1', $_GET['tourId']));
  if (!$tour) return;
  if ($tour->close_url) $tour->close_url = url($tour->close_url);
  if ($tour->exit_url) $tour->exit_url = url($tour->exit_url);

  // build startup settings (text values)
  $settings = array();
  foreach (array('text_of' => 'textOf', 'text_close' => 'textClose', 'btn_prev' => 'prevButton', 'btn_next' => 'nextButton') as $key => $val) {
    $settings[$val] = $tour->$key;
  }
  // build startup settings (boolean values)
  foreach (array('close_btn_action' => 'onCloseClickStay', 'cover_body' => 'doCoverBody', 'cover_click_close' => 'bodyCoverCloseOnClick') as $key => $val) {
    $settings[$val] = ($tour->$key == 1);
    if ($val == 'onCloseClickStay' && $tour->$key) {
      unset($tour->close_url);
    }
  }

  // build javascript code with startup settings
  $path = drupal_get_path('module', 'site_tour').'/lib/';
  $settings['BASE_URL'] = check_url(base_path() . $path);
  $output = '';
  foreach ($settings as $key => $value) {
    $pattern = "\n Amberjack.%key = %value;";
    $output .= strtr($pattern, array('%key' => $key, '%value' => drupal_to_js($value)));
  }
  drupal_add_js($output, 'inline', 'footer');
  drupal_add_js('$(document).ready(function() { Amberjack.open(); });', 'inline', 'footer', TRUE);

  return theme('site_tour', $tour);
}


/************************************************************
 * Show tour
 ************************************************************/

/**
 * Redirect to tour url.
 */
function site_tour_render($url = NULL) {
  if ($url) {
    if ($tour = db_fetch_object(db_query('SELECT * FROM {site_tour} WHERE url="%s" AND status=1', $url))) {
      if ($page = db_result(db_query('SELECT url FROM {site_tour_pages} WHERE tour=%d AND status=1 ORDER BY weight, title LIMIT 0,1', $tour->id))) {
        $query = array('tourId' => $tour->url, 'skinId' => $tour->skin);
        $destination = url($page, array('query' => $query));
        header('Location: '.$destination);
        exit();
      }
    }
  }
  drupal_not_found();
}


/************************************************************
 * Theme functions
 ************************************************************/

function theme_site_tour($tour) {
  if ($tour->exit_url) {
    $exit_url = '<div title="%exit_url"></div>';
  }

  // build tour pages
  $tour->pages = '';
  $sql = db_query('SELECT * FROM {site_tour_pages} WHERE tour=%d AND status=1 ORDER BY weight, title', $tour->id);
  while ($page = db_fetch_object($sql)) {
    $tour->pages .= theme('site_tour_page', $page);
  }
  
  $output = <<<CODE
<!-- Tour created with Amberjack wizard: http://amberjack.org -->
<div class="ajTourDef" id="%id" style="display:none" title="%close_url">
  %pages
  {$exit_url}
</div>

CODE;

  return strtr($output, array('%id' => $tour->url, '%close_url' => $tour->close_url,
    '%pages' => $tour->pages, '%exit_url' => $tour->exit_url));
}

function theme_site_tour_page($page) {
  $current = drupal_get_normal_path($page->url) == $_GET['q'];
  $output = <<<CODE
    <div id="site_tour_page_%id" title="%url">
      <strong>%title</strong> %description
    </div>

CODE;

  $url = '/'.trim(url($page->url, array('language' => '')), '/');
  return strtr($output, array('%id' => $page->page, '%url' => $url, 
    '%title' => theme('placeholder', $page->title), '%description' => $page->description));
}