<?php
// $Id: taxonomy_hide.module,v 1.9.4.4 2008/10/27 23:35:52 brmassa Exp $

/**
 * @file
 */

/**
 * Implementation of hook_menu().
 */
function taxonomy_hide_menu() {
  $items['admin/settings/taxonomy_hide'] = array(
    'access arguments'  => array('administer taxonomy'),
    'description'       => 'Hide and group vocabulary terms in node views.',
    'file'              => 'taxonomy_hide.admin.inc',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('_taxonomy_hide_admin_settings'),
    'title'             => 'Taxonomy hide',
  );
  return $items;
}

/**
 * Implementation of hook_help().
 */
function taxonomy_hide_help($path, $args) {
  switch ($path) {
    case 'admin/settings/taxonomy_hide':
      return t('The module allows you to hide and group vocabulary terms in node views.');

    case 'admin/help#taxonomy_hide':
      return
        '<p>'. t('The module allows you to hide and group vocabulary terms in node views.') .'</p>'.
        '<p>'. t('When you view a node, you usually see all vocabulary terms it is associated with. Sometimes, you might want to hide terms of a specific vocabulary. This module allows you to specify the vocabularies whose terms are never displayed in node views.') .'</p>'.
        '<p>'. t('The list of vocabulary terms is usually sorted first by vocabulary weight, and next alphabetically. So terms of different vocabularies with the same weight are mixed. This module allows you to group terms by vocabulary in node views, which means that all terms of one vocabulary are always next to each other.') .'</p>'.
        '<p>'. t('You can') .'</p>'.
        '<ul><li>'. t('Specify vocabularies whose terms will be hidden at <a href="@admin">Administer &gt; Site configuration &gt; Taxonomy hide</a>.') .'</li>'.
        '<li>'. t('Enable grouping of vocabulary terms at <a href="@admin">Administer &gt; Site configuration &gt; Taxonomy hide</a>.', array('@admin' => url('admin/settings/taxonomy_hide'))) .'</li></ul>';
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function taxonomy_hide_nodeapi(&$node, $op, $arg = 0, $arg2 = 0) {
  switch ($op) {
    case 'view':
      include_once drupal_get_path('module', 'taxonomy_hide') .'/taxonomy_hide.inc';
      _taxonomy_hide_nodeapi($node, $op, $arg, $arg2);
      break;
  }
  return;
}
