<?php

/********************************************************************
 * Constants
 ********************************************************************/

define("cLinkPointGAPIURL" ,"https://secure.linkpt.net:1129/LSGSXML");

/********************************************************************
 * Drupal Hooks
 ********************************************************************/

/**
 * Implementation of hook_menu()
 */
function pg_linkpoint_menu() {
  $items['admin/pgdata/pgsettings/linkpoint'] = array(
      'title'           => 'Linkpoint',
      'description'     => 'Linkpoint payment settings.',
      'page callback'   => 'drupal_get_form',
      'page arguments'  => array('pg_linkpoint_settings'),
      'access callback' => 'user_access',
      'access arguments' => array('administer pgapi'),
      'file'            => 'pg_linkpoint.admin.inc',
      'type'            => MENU_LOCAL_TASK,
  );
  return $items;
}

/********************************************************************
 * Pgapi Gateway Hooks
 ********************************************************************/
function pg_linkpoint_pgapi_gw($op,$a3=NULL,$a4=NULL){
  switch($op){
    case 'display name':
        $ret = t('Linkpoint Global API Payment Gateway');
      break;
    case 'payment gateway info':
        $ret['name']=t('Linkpoint');
        $prices['USD'] = $a3*variable_get('pg_linkpoint_rate','1.00');;
        $ret['price']= $prices;
      break;
    case 'process form':
        $form_result = $a4;
        $t = $a3;
        $ret = pg_linkpoint_process_form($form_result,$t);
      break;
    case 'get form':
        $ret = pg_linkpoint_extraform();
      break;

  }
  return $ret;
}

function pg_linkpoint_pgapi_transaction($status,&$t){
  switch($status){
    case PG_PENDING:
        $t->extra['amount'] =  $t->amount * variable_get('pg_linkpoint_rate','1.00');
      break;
  }
}

function pg_linkpoint_extraform(){
  $form['cc'] = array(
    '#type' => 'fieldset',
    '#title' => t('Credit Card'),
  );
  $form['cc']['cart_owner'] = array(
    '#type' => 'textfield',
    '#title' => t('Card Owner')
  );

  $form['cc']['cart_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Card Number'),
  );
  $options=array(
    '01' => '01',
    '02' => '02',
    '03' => '03',
    '04' => '04',
    '05' => '05',
    '06' => '06',
    '07' => '07',
    '08' => '08',
    '09' => '09',
    '10' => '10',
    '11' => '11',
    '12' => '12',
  );
  $form['cc']['exp_month'] = array(
    '#type' => 'select',
    '#title' => t('Expiration Month'),
    '#options' => $options
  );
  $options=array(
    '09' => '09',
    '10' => '10',
    '11' => '11',
    '12' => '12',
    '13' => '13',
    '14' => '14',
    '15' => '15',
    '16' => '16',
    '17' => '17',
    '18' => '18',
    '19' => '19',
    '20' => '20',
  );
  $form['cc']['exp_year'] = array(
    '#type' => 'select',
    '#title' => t('Expiration Year'),
    '#options' => $options
  );
  $form['cc']['cvv'] = array(
    '#type' => 'textfield',
    '#title' => t('Security Code'),

  );
  return $form;
}

function pg_linkpoint_process_form($form_result,$t){
  $amount = number_format($t->amount * variable_get('pg_linkpoint_rate','1.00'),2);

 /******************************************************************************/

  $xml ="<order>";

  $xml .="<billing>";
  $xml .="<name>" . $t->extra['billing_addr']['first_name']. " " . $t->extra['billing_addr']['last_name'] . "</name>"."\n";
  $xml .="<company>" . $t->extra['billing_addr']['company'] . "</company>"."\n";
  $xml .="<address1>" . $t->extra['billing_addr']['address'] . "</address1>"."\n";
  $xml .="<address2></address2>"."\n";
  $xml .="<addrnum>" .$t->extra['billing_addr']['address']. "</addrnum>"."\n";
  $xml .="<city>" . $t->extra['billing_addr']['city'] . "</city>"."\n";
  $xml .="<state>" . $t->extra['billing_addr']['state']. "</state>"."\n";
  $xml .="<zip>" . $t->extra['billing_addr']['postal_code'] . "</zip>"."\n";
  $xml .="<country>" . $t->extra['billing_addr']['country'] . "</country>"."\n";
  $xml .="<phone>" .$t->extra['billing_addr']['phone'] ."</phone>"."\n";
  $xml .="<email>" . $t->email . "</email>"."\n";
  $xml .="</billing>"."\n";

  $xml .="<shipping>"."\n";
  $xml .="<name>" . $t->extra['shipping_addr']['first_name']. " " . $t->extra['shipping_addr']['last_name'] . "</name>"."\n";
  $xml .="<address1>" . $t->extra['shipping_addr']['address'] . "</address1>"."\n";
  $xml .="<address2></address2>"."\n";
  $xml .="<city>" . $t->extra['shipping_addr']['city'] . "</city>"."\n";
  $xml .="<state>" . $t->extra['shipping_addr']['state']. "</state>"."\n";
  $xml .="<zip>" . $t->extra['shipping_addr']['postal_code'] . "</zip>"."\n";
  $xml .="<country>" . $t->extra['shipping_addr']['country'] . "</country>"."\n";
  $xml .="</shipping>"."\n";

  $xml .="<orderoptions>"."\n";
  $xml .="<result>" . variable_get('pg_linkpoint_transaction_mode', '') . "</result>"."\n";
  $xml .="<ordertype>" . variable_get('pg_linkpoint_transaction_method', '') . "</ordertype>"."\n";
  $xml .="</orderoptions>"."\n";

  $xml .="<merchantinfo>"."\n";
  $xml .="<configfile>" . variable_get('pg_linkpoint_login_id', '') . "</configfile>"."\n";
  $xml .="</merchantinfo>"."\n";

  $xml .="<creditcard>"."\n";
  $xml .="<cardnumber>" . $form_result['cc']['cart_number'] . "</cardnumber>"."\n";
  $xml .="<cardexpmonth>" . $form_result['cc']['exp_month'] . "</cardexpmonth>"."\n";
  $xml .="<cardexpyear>" . $form_result['cc']['exp_year'] . "</cardexpyear> "."\n";
  $xml .="<cvmvalue>" . $form_result['cc']['cvv'] . "</cvmvalue>"."\n";
  $xml .="<cvmindicator>provided</cvmindicator>"."\n";
  $xml .="</creditcard>"."\n";

  $xml .="<payment>"."\n";
  $xml .="<chargetotal>" . $amount . "</chargetotal>"."\n";
  $xml .="</payment>"."\n";

  $xml .="<transactiondetails>"."\n";
  $xml .="<transactionorigin>ECI</transactionorigin>"."\n";
  $xml .="<oid>" . $t->txnid . "</oid>"."\n";
  $xml .="<ip>" . $_SERVER['REMOTE_ADDR'] . "</ip>"."\n";
  $xml .="</transactiondetails>"."\n";

  $xml .="<notes>"."\n";
  $xml .="<comments>" . t('Buying ticket(s) from Umatax') . "</comments>"."\n";
  $xml .="</notes>"."\n";

  $xml .="</order>"."\n";

 /******************************************************************************/

  $fid = variable_get('pg_linkpoint_transaction_key_fid', '');
  $file=db_fetch_object(db_query("SELECT * FROM {files} WHERE fid = '%d'", $fid));
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, variable_get('pg_linkpoint_action_url',cLinkPointGAPIURL));
  curl_setopt($ch, CURLOPT_VERBOSE, 0);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $xml);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_SSLCERT, $file->filepath);
  //curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
  $buffer = curl_exec($ch);

  if ($error = curl_error($ch)) {
    watchdog('uc_linkpoint_api', $error, WATCHDOG_ERROR);
  }
  curl_close($ch);

  if (strlen($buffer) < 2) {
    $buffer = "<r_error>Sorry - Could not connect to payment gateway.</r_error>";
  }
  preg_match_all ("/<(.*?)>(.*?)\</", $buffer, $outarr, PREG_SET_ORDER);

  $n = 0;
  while (isset($outarr[$n])) {
    $retarr[$outarr[$n][1]] = strip_tags($outarr[$n][0]);
    $n++;
  }

  $response = split('\,', $buffer);
  $x_response_code = $retarr['r_approved'];
  $x_response_text = $retarr['r_error'];
  $x_approval_code = $retarr['r_code'];

  if ($x_response_code != 'APPROVED') {
    $res = t('Credit card declined. Error: !error, code:!code', array('!error' => $x_response_text, '!code' => $x_approval_code));
    $status = 'denied';
  } else {
    $res = t('Credit card charged');
    $status = 'completed';
  }

  $t->description=$res;
  $t->status = pgapi_get_status_id($status);
  pgapi_transaction_save($t);
  return $t;
}
