<?php

/**
 * Implementation of hook_init().
 */
function atrium_home_init() {
  drupal_add_css(drupal_get_path('module', 'atrium_home') . '/atrium_home.css');
}

/**
 * Implementation of hook_preprocess_page().
 * Here we do a few things to make the homepage the default tab for home
 * and hide the regular homepage tab unless we are in a group context.
 */
function atrium_home_preprocess_page(&$vars) {
  $space = module_exists('spaces') ? spaces_get_space() : FALSE;
  
  if (!$space || $space->type != 'og') {
    foreach ($vars['primary_links'] as $k => &$link) {
      if (drupal_is_front_page()) {
        if ($link['href'] == 'homepage') {
          $link['attributes'] = array('class' => 'active');
          $vars['primary_links'][$k .' active-trail active'] = $link;
          unset($vars['primary_links'][$k]);
        }
        elseif ($link['attributes']['class']) {
          $link['attributes']['class'] = str_replace('active', '', $link['attributes']['class']);
        }
      }
      if ($link['href'] == variable_get('site_frontpage', 'dashboard')) {
        unset($vars['primary_links'][$k]);
      }
    }
  }
}

/**
 * Implementation of hook_menu().
 */
function atrium_home_menu() {
	$items = array();
	$items['homepage'] = array(
		'title' => t('Home'),
		'menu_name' => 'features',
		'page callback' => 'atrium_home_redirect',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}

/**
 * Uses purl_goto to redirect users to the home page
 */
function atrium_home_redirect() {
  purl_goto('<front>', array('purl' => array('disabled' => true)));
}

/*
 * Implementation of hook_form_FORM_ID_alter().
 * Removing the Home page as the default frontpage, because
 * that would cause redirect loops and be generally BAD.
 */
function atrium_home_form_spaces_features_form_alter(&$form, $form_state) {
  unset($form['site_frontpage']['#options']['homepage']);
}