<?php

/********************************************************************
 * Constants
 ********************************************************************/

define("c2coActionUrlSingle" ,"https://www.2checkout.com/checkout/spurchase");
define("c2coActionUrlMulti" ,"https://www.2checkout.com/checkout/spurchase");

/********************************************************************
 * Drupal Hooks
 ********************************************************************/


/**
 * Implementation of hook_menu()
 */
function pg_2co_menu() {
  $items['2co/done'] = array(
      'title'           => 'Internal Data',
      'page callback'   => 'pg_2co_done_payment',
      'access callback' => TRUE,
      'file'            => 'pg_2co.admin.inc',
      'type'            => MENU_CALLBACK
  );
  $items['admin/pgdata/pgsettings/2co'] = array(
      'title'           => '2co',
      'description'     => '2co payment settings.',
      'page callback'   => 'drupal_get_form',
      'page arguments'  => array('pg_2co_settings'),
      'access callback' => 'user_access',
      'access arguments' => array('administer pgapi'),
      'file'            => 'pg_2co.admin.inc',
      'type'            => MENU_LOCAL_TASK,
  );
  return $items;
}

/********************************************************************
 * Pgapi Gateway Hooks
 ********************************************************************/
function pg_2co_pgapi_gw($op,$a3=NULL,$a4=NULL){
  switch($op){
    case 'display name':
        $ret = t('2co Payment Gateway');
      break;
    case 'payment gateway info':
        $ret['name']=t('2co');
        $prices[variable_get('pg_2co_currency_code','USD')] = round(($a3*variable_get('pg_2co_rate','1.00')),2);
        $ret['price']= $prices;
      break;
    case 'get form':
        $t=$a3;
        $form_result = $a4;
        $ret = pg_2co_extraform($form_result,$t);
      break;
    case 'process form':
        $form_result = $a4;
        $t = $a3;
        $ret = pg_2co_process_form($form_result,$t);
      break;
  }
  return $ret;
}

function pg_2co_pgapi_transaction($status,&$t){
  switch($status){
    case PG_PENDING:
        $t->extra['amount'] =  round(($t->amount * variable_get('pg_2co_rate','1.00')),2);
      break;
  }
}
function pg_2co_extraform($form_state,$t){
  $form['message'] = array(
    '#type' => 'markup',
    '#value' => t('We will charge !amount from your CC', array ('!amount' => round(($t->amount * variable_get('pg_2co_rate','1.00')),2))),
  );
  return $form;
}

function pg_2co_process_form($form_result,$t){
  $output = drupal_get_form('pg_2co_payform',$form_state,$t);
  //$output = str_ireplace('accept-charset="UTF-8"','accept-charset="cp1251"',$output);
  $t->method='2co';
  pgapi_transaction_save($t);
  echo '<html><body>'.$output.'<script>pgpayform.submit();</script></body>';
//  echo '<html><body>'.$output.'</body>';
  exit();
}

function pg_2co_payform($form_state,$post,$t) {
  global $user;


/*
 $data = array(
    'sid' => variable_get('uc_2checkout_sid', ''),
    'total' => uc_price($order->order_total, $context, $options),
    'cart_order_id' => $order->order_id,
    'demo' => variable_get('uc_2checkout_demo', TRUE) ? 'Y' : 'N',
    'fixed' => 'Y',
    'lang' => variable_get('uc_2checkout_language', 'en'),
    'x_receipt_link_url' => url('cart/2checkout/complete/'. uc_cart_get_id(), array('absolute' => TRUE)),
    'merchant_order_id' => $order->order_id,
    'pay_method' => isset($_SESSION['pay_method']) ? $_SESSION['pay_method'] : 'CC',
    'card_holder_name' => substr($order->billing_first_name .' '. $order->billing_last_name, 0, 128),
    'street_address' => substr($order->billing_street1, 0, 64),
    'street_address2' => substr($order->billing_street2, 0, 64),
    'city' => substr($order->billing_city, 0, 64),
    'state' => uc_get_zone_code($order->billing_zone),
    'zip' => substr($order->billing_postal_code, 0, 16),
    'country' => $country[0]['country_iso_code_3'],
    'email' => substr($order->primary_email, 0, 64),
    'phone' => substr($order->billing_phone, 0, 16),
    'id_type' => 1,
  );*/

  $form['sid'] = array(
    '#type' => 'hidden',
    '#default_value' => variable_get('pg_2co_sid',''),
  );

  $amount = number_format($t->amount * variable_get('pg_2co_rate','1.00'),2);
  $form['total'] = array(
    '#type' => 'hidden',
    '#default_value' => $amount,
  );
  $form['cart_order_id'] = array(
    '#type' => 'hidden',
    '#default_value' => $t->txnid,
  );
  $form['demo'] = array(
    '#type' => 'hidden',
    '#default_value' => variable_get('pg_2co_demo', TRUE),
  );
  $form['lang'] = array(
    '#type' => 'hidden',
    '#default_value' => variable_get('pg_2co_language', 'en'),
  );
  $form['x_receipt_link_url'] = array(
    '#type' => 'hidden',
    '#default_value' => url('2co/success', array('absolute' => TRUE)),
  );
  $form['#attributes'] = array('name' => 'pgpayform');
  $form['#action'] = variable_get('pg_2co_action_url',c2coActionUrlSingle);
  return $form;
}
