<?php

/**
 * @file
 * Allows the use of checkboxes, radio buttons or hidden fields for exposed Views filters.
 *
 * Thanks to Ben Buckman (http://echodittolabs.org/) for the original concept.
 */

/**
 * Implements hook_theme()
 */
function better_exposed_filters_theme($existing, $type, $theme, $path) {
  return array(
    'select_as_checkboxes'          => array('function' => 'theme_select_as_checkboxes',
                                             'file' => 'better_exposed_filters.theme'),
    'select_as_checkboxes_fieldset' => array('function' => 'theme_select_as_checkboxes_fieldset',
                                             'file' => 'better_exposed_filters.theme'),
    'select_as_radios'              => array('function' => 'theme_select_as_radios',
                                             'file' => 'better_exposed_filters.theme'),
    'select_as_radios_fieldset'     => array('function' => 'theme_select_as_radios_fieldset',
                                             'file' => 'better_exposed_filters.theme'),
    'select_as_hidden'              => array('function' => 'theme_select_as_hidden',
                                             'file' => 'better_exposed_filters.theme'),
    'select_as_tree'                => array('function' => 'theme_select_as_tree',
                                             'file' => 'better_exposed_filters.theme'),
    'select_as_links'               => array('function' => 'theme_select_as_links',
                                             'file' => 'better_exposed_filters.theme'),
  );
}


/**
 * Implements hook_views_api()
 */
function better_exposed_filters_views_api() {
  return array(
    'api' => 3.0,
  );
}

/**
 * Helper function for combining exposed sort criteria and direction
 */
function bef_sort_combine_submit($form, &$form_state) {
  // Unpack sort_by and sort_order from the sort_bef_combine element
  if (empty($form_state['values']['sort_bef_combine'])) {
    $form_state['values']['sort_by'] = $form_state['values']['sort_order'] = '';
  }
  else {
    list($form_state['values']['sort_by'], $form_state['values']['sort_order']) =
        explode(' ', $form_state['values']['sort_bef_combine']);
  }

  // And pass this along to Views
  views_exposed_form_submit($form, $form_state);
}
