<?php
//$id$
/**
 * @file
 * 		Atrium User Roles
 * 		Fixes the ability to control roles per group in the members sections
 * 
 * @author
 * 		Greg Gunner
 */

/**
 * Implemenation of hook_menu
 * 
 */
function atrium_user_roles_menu()
{
  $items['members/roles'] = array(
    'title' => 'Configure roles',
    'page callback' => 'atrium_user_roles_page',
    'access callback' => 'atrium_user_roles_access',
    'weight' => 5,
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Dummy page to return the page og_user_roles_page
 * 
 */
function atrium_user_roles_page()
{
	$node = og_get_group_context();
	if ($node) {
		module_load_include('inc', 'og_user_roles', 'og_user_roles.pages');
		return og_user_roles_page($node);
	}
}

/**
 * Dummy access control function to call og_user_roles_is_allowed
 * 
 */
function atrium_user_roles_access()
{
	$node = og_get_group_context();
	if ($node) {
		return og_user_roles_is_allowed($node);
	} else {
		return FALSE;
	}
}
