<?php
// $id$

/**
 * Implementation of hook_menu()
 */
function pg_fundraising_giftaid_menu() {
  //admin
  $items['admin/pgdata/fundraising/giftaid'] = array(
    'title'            => 'GiftAid settings',
    'description'      => 'Configure GiftAid feature.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('pg_fundraising_giftaid_admin'),
    'access callback'  => 'user_access',
    'access arguments' => array('administer fundraising tools'),
    'file'             => 'pg_fundraising_giftaid.admin.inc',
    'type'             => MENU_NORMAL_ITEM,

  );
  return $items;
}


/**
 * Implementation of hook_pg_fundraising_tax()
 */
function pg_fundraising_giftaid_pg_fundraising_tax($op, $values = array(), $form_state = array()) {

  switch ($op) {
    case 'tax option':
      $info = array(
        'name' => t('Gift aid'),
      ); 
      
      return $info;
      break;
    
    case 'form':
      //fieldset name
      $ret_val['name'] = 'GiftAid';
      $ret_val['description'] = variable_get('pg_fundraising_giftaid_desc', '');
      
      //form
      $ret_val['form']['giftaid_options'] = array(
        '#title'         => t('I am'),
        '#type'          => 'radios',
        '#options'       => array('giftaid' => t('a UK taxpayer and would like to Gift Aid all donations.'),
                            'no_giftaid' => t('not a UK tax payer.'),
                           ),
        '#required'      => TRUE,
      );
      
      return $ret_val;
      
      break;
      
    case 'save':
      // save the giftaid information
      if ($form_state['values']['giftaid_options'] == 'giftaid') {
        drupal_write_record('fundraising_giftaid', $values);  
      }
      
      break;
  }
  
}

function pg_fundraising_giftaid_form_alter(&$form, $form_state, $form_id) {

  if ($form_id == 'pg_fundraising_donation_form') {
    // add validate and submit handlers
    $form['#validate'][] = 'pg_fundraising_giftaid_form_validate';
    //$form['#submit'][] = 'pg_fundraising_giftaid_form_submit'; 
  }
}


function pg_fundraising_giftaid_form_validate(&$form, &$form_state) {
  
  if ($form_state['values']['giftaid_options'] != 'giftaid') {
     $form_state['values']['giftaid_options'] != 'no_giftaid';
  }
}

//function pg_fundraising_giftaid_form_submit(&$form, $form_state) {
//    dsm('submitting...');
//}