<?php

include_once('atrium_discussion.features.inc');

/**
 * Implementation of hook_init()
 */

function atrium_discussion_init() {
  drupal_add_css(drupal_get_path('module', 'atrium_discussion') . '/atrium_discussion.css');
}

/**
 * Implementation of hook_help().
 */
function atrium_discussion_help($path) {
  // Central help page content.
  if ($path == 'help#atrium_discussion') {
    $help = '<h3>'. t('Discussion') .'</h3>';
    $help .= '<p>'. t("The discussion area lets your team communicate by posting updates and discussing issues. It is a great place for sharing progress, discussing challenges, and exploring ideas.") .'</p>';
    $help .= '<p>'. t("To start a conversation navigate to the discussion and click the \"Add discussion\" button. You will need to enter a title and some body content to your post. Then click \"Save\".") .'</p>';
    return $help;
  }

  // Contextual help content.
  if (context_isset('context', 'discussion_listing')) {
    if ($path == 'node/add/discussion') {
      $help = '';
      $help .= '<h3>'. t('Discussion') .'</h3>';
      $help .= '<p>'. t("Post an entry to the discussion of this group. The post will be shared will all team members, and they will be able to reply to it. You can optionally notify other group members by checking their name in the notifications field.") .'</p>';
      return $help;
    }
    else {
      $help = '<h3>'. t('Discussion') .'</h3>';
      $help .= '<p>'. t("The discussion area lets your team communicate by posting updates and discussing issues. It is a great place for sharing progress, discussing challenges, and exploring ideas.") .'</p>';
      return $help;
    }
  }
}
